### ISSUE TITLE
Problem installing angular-tag via bower

### ISSUE THREAD

**Issue by mcmahonjohn** [theo4u/angular-tag#3]
`bower install --save-dev angular-tag`

> bower angular-tag#1.0.0**UNABLE_TO_VERIFY_LEAF_SIGNATURE** Request to https://bower.herokuapp.com/packages/angular-tag failed: unable to verify the first certificate

**Comment by Auwalms** [comment]
@mcmahonjohn 
Please refer to [this issue](https://github.com/bower/bower/issues/468) on bower for solution to this problem. 
Thanks
